apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
  labels:
    dashboards: "grafana"
spec:
  config:
    security:
      admin_user: admin
      admin_password: admin
---
# apiVersion: grafana.integreatly.org/v1beta1
# kind: GrafanaDatasource
# metadata:
#   name: example-grafanadatasource
# spec:
#   datasource:
#     access: proxy
#     type: prometheus
#     jsonData:
#       timeInterval: 5s
#       tlsSkipVerify: true
#     name: Prometheus
#     url: http://prometheus-service:9090
#   instanceSelector:
#     matchLabels:
#       dashboards: grafana
#   plugins:
#     - name: grafana-clock-panel
#       version: 1.3.0
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-http-route
  namespace: monitoring
spec:
  parentRefs:
    - name: default-web
      namespace: default
  hostnames:
    - "tuscany.localhost"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: grafana-service
          port: 3000
